### ISSUE TITLE
0.7打印版发现的问题

### ISSUE THREAD

**Issue by qwedfvbn** [jiangming1399/tae-kim_cn_latex_go#4]
p26 方框内容错误  表示状态的时候可以把「だ」都省去！

p27     这页似乎应该全改为（な）形容词？
           （な）だ形容词后面来表示否定
　　　 将「じゃない」加在名词或者（な）だ形容词后面
               要想表达某物曾是什么，就把「だった」加在名词或者（な）だ形容词后面。

p32 主要区别在于用な形容词形容词修饰名词的时候       文中（形容词）多了一个

p35 第一个方框内容错误 不要在い形容词后面加「だ」！

p46 单词表  街【まち】- 城镇    城镇改为街道 

p53 单词翻译
開ける-打开（门、窗等） 開く-（门、窗等）开着   
閉める-关闭（门、窗等） 閉める-（门、窗等）关着 
つける-打开（电灯、空调等） つく-（电灯、空调等）开着 
    消す-关闭（电灯、空调等） 消える-（电灯、空调等）关着

**Comment by jim-kirisame** [comment]
内容上的问题建议到[原作者的博客](https://blog.wokanxing.info/)下面去反映，这里就基本上只处理转换过程中的问题。

**Comment by pizzamx** [comment]
> 内容上的问题建议到[原作者的博客](https://blog.wokanxing.info/)下面去反映，这里就基本上只处理转换过程中的问题。

看到了看到了……

**Comment by qwedfvbn** [comment]
> 内容上的问题建议到[原作者的博客](https://blog.wokanxing.info/)下面去反映，这里就基本上只处理转换过程中的问题。

你好，方框内容的错误，原网页版没有出现这样的问题，应该属于转换过程中的问题。

p26 方框内容错误 表示状态的时候可以把「だ」都省去！
p35 第一个方框内容错误 不要在い形容词后面加「だ」！

**Comment by jim-kirisame** [comment]
好的，我找个时间修复一下

**Comment by pizzamx** [comment]
> > 内容上的问题建议到[原作者的博客](https://blog.wokanxing.info/)下面去反映，这里就基本上只处理转换过程中的问题。
> 
> 你好，方框内容的错误，原网页版没有出现这样的问题，应该属于转换过程中的问题。
> 
> p26 方框内容错误 表示状态的时候可以把「だ」都省去！
> p35 第一个方框内容错误 不要在い形容词后面加「だ」！

已经更新到 [https://res.wokanxing.info/jpgramma/](https://res.wokanxing.info/jpgramma/)，后续有问题可以去[我那里](https://github.com/pizzamx/jpgramma)提 PR 哈

**Comment by jim-kirisame** [comment]
修好了~
